server:
  port: 18700

spring:
  application:
    name: billbatch
  datasource:
    url: jdbc:oracle:thin:@192.168.2.200:1521:ORCL
    username: heart
    password: 825919026


eureka:
  instance:
    appname: billbatch
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://192.168.2.200:8761/eureka/


mybatis:
  config-location: classpath:mybatis/mybatis.xml
  mapperLocations: classpath:mybatis/mapper/*.xml

#附件下载地址
AttachPath: "E:\\temp"




